#!/usr/bin/env node
// @effect-diagnostics nodeBuiltinImport:off - WSL-only build bootstrap and package-manager subprocess wrapper.
import * as NodeCrypto from "node:crypto";
import * as NodeFS from "node:fs";
import * as NodePath from "node:path";
import * as NodeChildProcess from "node:child_process";
import * as NodeURL from "node:url";

import {
  fingerprintPaths,
  pruneCache,
  restoreCache,
  saveCache,
} from "./lib/windows-build-cache.ts";

const repoRoot = NodeURL.fileURLToPath(new URL("..", import.meta.url));
const mode = process.argv[2];
if (mode !== "build" && mode !== "dependencies") throw new Error("Expected build or dependencies");
const cwd = mode === "build" ? repoRoot : process.cwd();
const cacheRoot = process.env.T3CODE_WINDOWS_BUILD_CACHE;
const args = mode === "build" ? ["run", "build:desktop"] : ["install", "--prod"];

function installedToolInputs(): { dependencyMetadata: string[]; tools: string[] } {
  const dependencyMetadata = ["node_modules/.modules.yaml", "node_modules/.pnpm/lock.yaml"].map(
    (path) => NodePath.join(repoRoot, path),
  );
  const tools = [
    "node_modules/.bin/vp",
    "node_modules/.bin/tsgo",
    "node_modules/.bin/esbuild",
    "apps/desktop/node_modules/.bin/electron-builder",
    "apps/desktop/node_modules/.bin/vp",
    "apps/server/node_modules/.bin/tsdown",
    "apps/web/node_modules/.bin/vite",
  ].map((path) => NodePath.join(repoRoot, path));
  const markers = [...tools];
  const markerCount = markers.length;
  for (let index = 0; index < markerCount; index += 1) {
    const marker = markers[index]!;
    try {
      const resolved = NodeFS.realpathSync(marker);
      if (resolved !== marker) markers.push(resolved);
    } catch {
      // Missing optional tools remain represented by their marker path.
    }
  }
  return { dependencyMetadata, tools: markers };
}

function output(command: string, args: string[]): string {
  return NodeChildProcess.execFileSync(command, args, {
    cwd: repoRoot,
    encoding: "utf8",
    maxBuffer: 64 * 1024 * 1024,
  }).trim();
}

function run() {
  const result = NodeChildProcess.spawnSync("vp", args, { cwd, stdio: "inherit" });
  if (result.error) throw result.error;
  if (result.status !== 0)
    throw new Error(`vp ${args.join(" ")} failed (${result.status ?? result.signal})`);
}

if (!cacheRoot) {
  run();
} else {
  const started = performance.now();
  const workspaceDirs = ["apps", "packages", "infra"].flatMap((parent) =>
    NodeFS.readdirSync(NodePath.join(repoRoot, parent), { withFileTypes: true })
      .filter((entry) => entry.isDirectory())
      .map((entry) => NodePath.join(repoRoot, parent, entry.name)),
  );
  const roots = [
    repoRoot,
    ...workspaceDirs,
    NodePath.join(repoRoot, "scripts"),
    NodePath.join(repoRoot, "oxlint-plugin-t3code"),
  ];
  const inputs =
    mode === "build"
      ? output("git", ["ls-files", "-z", "--", ".", ":(exclude).repos/**"])
          .split("\0")
          .filter(Boolean)
          .map((path) => NodePath.join(repoRoot, path))
      : ["pnpm-workspace.yaml", "patches"].map((path) => NodePath.join(cwd, path));
  // Vite reads app-local mode files as well as loadRepoEnv's root files.
  inputs.push(
    ...roots.flatMap((root) =>
      NodeFS.readdirSync(root)
        .filter((name) => name === ".npmrc" || name.startsWith(".env"))
        .map((name) => NodePath.join(root, name)),
    ),
  );
  inputs.push(
    NodePath.join(repoRoot, "pnpm-lock.yaml"),
    NodePath.join(repoRoot, "pnpm-workspace.yaml"),
    NodePath.join(repoRoot, "patches"),
    NodeURL.fileURLToPath(import.meta.url),
    NodeURL.fileURLToPath(new URL("./lib/windows-build-cache.ts", import.meta.url)),
  );
  // Staged manifests are generated by the artifact builder. Release metadata
  // changes every commit but cannot change this dependency installation.
  const manifest =
    mode === "dependencies"
      ? (JSON.parse(NodeFS.readFileSync(NodePath.join(cwd, "package.json"), "utf8")) as Record<
          string,
          unknown
        >)
      : undefined;
  const dependencyManifest =
    manifest === undefined
      ? undefined
      : Object.fromEntries(
          Object.entries(manifest).filter(
            ([name]) =>
              ![
                "version",
                "buildVersion",
                "t3codeCommitHash",
                "description",
                "author",
                "main",
                "build",
              ].includes(name),
          ),
        );
  const environment = Object.entries(process.env)
    .filter(([name]) => !["_", "PWD", "OLDPWD", "SHLVL"].includes(name))
    .sort(([a], [b]) => a.localeCompare(b));
  const key = NodeCrypto.createHash("sha256")
    .update(
      JSON.stringify({
        mode,
        inputs: fingerprintPaths(inputs),
        dependencyManifest,
        installed:
          mode === "build"
            ? (() => {
                const installed = installedToolInputs();
                return {
                  dependencyMetadata: fingerprintPaths(installed.dependencyMetadata),
                  tools: fingerprintPaths(installed.tools),
                };
              })()
            : undefined,
        environment,
        node: process.version,
        vp: output("vp", ["--version"]),
        // oxlint-disable-next-line t3code/no-global-process-runtime -- Standalone Node bootstrap; no Effect runtime.
        platform: process.platform,
        // oxlint-disable-next-line t3code/no-global-process-runtime -- Cache native dependencies for this bootstrap host.
        arch: process.arch,
        commit: mode === "build" ? output("git", ["rev-parse", "HEAD"]) : undefined,
      }),
    )
    .digest("hex");
  const entry = NodePath.join(cacheRoot, mode, key);
  const destinations = (
    mode === "build"
      ? ["apps/web/dist", "apps/server/dist", "apps/desktop/dist-electron"]
      : ["node_modules"]
  ).map((path) => NodePath.join(cwd, path));
  if (restoreCache(entry, destinations)) {
    process.stdout.write(
      `[windows-cache] Restored ${mode}; fingerprint and restore took ${((performance.now() - started) / 1000).toFixed(1)}s.\n`,
    );
  } else {
    process.stdout.write(
      `[windows-cache] ${mode} cache miss; fingerprint took ${((performance.now() - started) / 1000).toFixed(1)}s.\n`,
    );
    run();
    saveCache(entry, destinations);
    pruneCache(NodePath.join(cacheRoot, mode), 2, entry);
  }
}
